language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.4.12
  - DJANGO_VERSION=1.5.7
# command to install dependencies
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r travisrequirements.txt
# command to run tests
script: python manage.py test

